appprofil_index:
    path:     /
    defaults: { _controller: "AppBundle:admin/AppProfil:index" }
    methods:  GET

appprofil_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:admin/AppProfil:show" }
    methods:  GET

appprofil_new:
    path:     /new
    defaults: { _controller: "AppBundle:admin/AppProfil:new" }
    methods:  [GET, POST]

appprofil_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:admin/AppProfil:edit" }
    methods:  [GET, POST]

appprofil_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:admin/AppProfil:delete" }
    methods:  DELETE
